MallMembership/Controllers/AddressController.cs
using MallMembership.BusinessLayer;
using MallMembership.CustomFilter;
using MallMembership.Entities;
using MallMembership.Utility;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static MallMembership.MallWorkflowStages;

namespace MallMembership.Controllers
{
   
    [MallWorflowFilter((int)WorkflowStages.ApplicantInfo, (int)WorkflowStages.AddressInfo)]
    public class AddressController : Controller
    {
        private readonly IStageBusiness getStageBusiness = new StageBusiness();
        private readonly IAddressBusiness _addressBusiness;

        public AddressController(IAddressBusiness addressBusiness)
        {
            _addressBusiness = addressBusiness;
        }

        /// <summary>
        /// This is responsible for displaying form for adding and editing address details
        /// </summary>
        /// <returns></returns>
        public ActionResult AddressInfo()
        {
            int highestCompletedStage = getStageBusiness.GetCompletedStage((int)Session["id"]);
            if(highestCompletedStage>=(int)WorkflowStages.AddressInfo)
            {
                AddressInfo addressInfo = _addressBusiness.GetAddressByIdBL((int)Session["id"]);
                Session["AddressId"] = addressInfo.AddressId;
                return View(addressInfo);
            }
            return View();
        }

        /// <summary>
        /// This is responsible for adding and editing address details into database
        /// </summary>
        /// <returns></returns>
        public ActionResult AddAddressInfo([Bind(Include ="Country,State,City,Street")]AddressInfo addressInfo)
        {
            if (ModelState.IsValid)
            {
                addressInfo.ApplicantId = (int)Session["id"];
                _addressBusiness.AddAddressBL(addressInfo);

                return RedirectToAction(Constants.EmploymentInfo, "Employment");
            }
            return View(Constants.AddressInfo);
            
        }
    }
}

MallMembership/Views/Address/AddressInfo.cshtml
@model MallMembership.Entities.AddressInfo
@{
    ViewBag.Title = "AddressInfo";
}
@{
    Html.RenderPartial("_ProgressBar");
}
<h2>AddressInfo</h2>
@using (Html.BeginForm("AddAddressInfo", "Address", new { @id = "createFormId" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Street, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Street, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Street, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @*@Html.LabelFor(model => model.ApplicantId, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <div class="col-md-10">
                @Html.HiddenFor(model => model.ApplicantId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ApplicantId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}
@section scripts{

    <script src="~/Scripts/ValidateAddress.js"></script>
}