MallMembership/Controllers/ApplicantController.cs
using MallMembership.BusinessLayer;
using MallMembership.CustomFilter;
using MallMembership.Entities;
using MallMembership.Utility;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using static MallMembership.MallWorkflowStages;

namespace MallMembership.Controllers
{
    [MallWorflowFilter((int)WorkflowStages.Begin,(int)WorkflowStages.ApplicantInfo)]
    public class ApplicantController : Controller
    {
        private readonly IApplicantBusiness _applicantBusiness;
  
        public ApplicantController(IApplicantBusiness applicantBusiness)
        {
            _applicantBusiness = applicantBusiness;
        }

        /// <summary>
        /// This is responsible for displaying form for adding and editing applicant details
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult ApplicantInfo()
        {
            try
            {
                if (Session["id"] == null)
                {
                    return View();
                }
                else
                {
                    ApplicantInfo applicantInfo = _applicantBusiness.GetApplicantByIdBL((int)Session["id"]);
                    return View(applicantInfo);
                }
            }
            catch(Exception ex)
            {
                return View(Constants.ErrorView);
            }

        }

        /// <summary>
        /// This is responsible for adding and editing applicant details into database
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult AddApplicantInfo([Bind(Include = "FirstName,LastName,PhoneNumber,Email")]ApplicantInfo applicantInfo)
        {
            if (ModelState.IsValid)
            {

                applicantInfo.UserAgent = HttpContext.Request.UserAgent;
                applicantInfo.ContentType = HttpContext.Request.ContentType;
                applicantInfo.IPAddress = HttpContext.Request.UserHostAddress;
                
                var val = Session["id"];
                if (val == null)
                {
                    if (_applicantBusiness.AddApplicantBL(applicantInfo))
                    {
                        ApplicantInfo applicant = _applicantBusiness.GetRecentApplicantBL();
                        Session["id"] = applicant.ApplicantId;
                    }
                }
                else
                {
                    _applicantBusiness.UpdateApplicantBL(applicantInfo);
                }

                return RedirectToAction(Constants.AddressInfo, "Address");
            }
            return View(Constants.ApplicantInfo);
        }
       
           
        }
    }

MallMembership/Views/Applicant/ApplicantInfo.cshtml
@model MallMembership.Entities.ApplicantInfo
@{
    ViewBag.Title = "ApplicantInfo";
}
@{
    Html.RenderPartial("_ProgressBar");
}

<h2>ApplicantInfo</h2>


@using (Html.BeginForm("AddApplicantInfo", "Applicant", new { @id = "createFormId" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @*@Html.LabelFor(model => model.ApplicantId, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <div class="col-md-10">
                @Html.HiddenFor(model => model.ApplicantId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ApplicantId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@section scripts{
    
    <script src="~/Scripts/ValidateApplicant.js"></script>
}